### ISSUE TITLE
questions about image shape

### ISSUE THREAD

**Issue by JIBSN** [constantinpape/torch-em#208] opened 2024-02-01 13:09 UTC
Hi,
I am now training micro-sam with a custom dataset. The shape of my raw imags is HxWx3 and the label's shape is HxW. I found an error  "File "/home/jovyan/.conda/micro-sam/lib/python3.10/site-packages/torch_em/data/segmentation_dataset.py", line 61, in __init__
    assert shape_raw == shape_label, f"{shape_raw}, {shape_label}"
AssertionError: (2048, 3), (2048, 2048)". 
I am confused with this error. Please give me some tips why it happens and how to solve it.

**Comment by anwai98** [comment] 2024-09-20 22:16
Hi @JIBSN,

I hope the issue is fixed now. I'll go ahead and close this for now. Feel free to reopen this if the issue persists or you want to discuss something similar in the lines of the aforementioned issue.

**Closed by anwai98** 2024-09-20 22:16 UTC
